### ISSUE TITLE
Waveguide solution does not match the one in the examples :(

### ISSUE THREAD

**Issue by angeris** [ianwilliamson/FDFD.jl#1]
Heya @ianwilliamson and co! 👋

I wanted to give you all a big thanks for the Julia code here: it's an awesome reference! :) (I may end up extending it later for some 3D work.)

Sadly, I'm running into some trouble running the main simulations. In particular, I've noticed that the resulting plots don't actually match those given in the example notebook, and I'm not quite sure as to why. This is the solution output I have for the second example ("straight waveguide"), versus the one given in [here](https://github.com/fancompute/FDFD.jl/blob/master/notebooks/Example_simulations.ipynb).

![image](https://user-images.githubusercontent.com/2515887/87834476-6323b200-c83f-11ea-8a6b-0b34b8805515.png)

I'll see if I can find anything, but at the moment I haven't been able to figure it out.

Thanks!

**Comment by angeris** [comment]
On the other hand, example 3 matches beautifully. I'm not sure if this is due to the change in the interface to `GeometricPrimitives.jl` or what exactly; I did have to update example 2 slightly for it to work.

**Comment by ianwilliamson** [comment]
What does the permittivity distribution look like for the simulation that you're showing above? Based on the fields and the profile of the source it looks like the waveguide may not be "drawn into" the domain. If the permittivity is uniform everywhere, then what you're observing would make sense.

It's likely that GeometricPrimitives.jl has been updated much more recently than this package, which could be why the waveguide isn't showing up. Feel free to submit a pull request for a fix if you can figure it out.

**Comment by angeris** [comment]
It seems that you're correct! (Generating the permittivity region manually seems to do the trick.)
![image](https://user-images.githubusercontent.com/2515887/87963500-a5323b00-ca6d-11ea-97c2-2f8956e5c5c5.png)


I'm not sure what the current interface to GeometricPrimitives.jl is (and sadly don't have much time to check/fix it today) but will take a look when I do! Thanks! I'll PR and reference this issue when I do.
